- name: download sapcar
  get_url:
    url: "{{ url_sapcar }}"
    dest: /hana/shared/install/SAPCAR_LINUX.EXE
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"