# Pipeline which deploys SAP HANA VM including filesystem layout and DB installation on RHEL or SUSE
# VM can be added to RSV including hana backup integration script run
# Testing consists of quality checks and HCMT
# 
# Todo:
#  Documentation
#  selective disk backup (exclude HANA Data and LOG from OS Backups)
#  use SSH key and passwords from KeyVault
#  friendly names for disks, helps identify disks to exclude form OS backup
#  execute the HANA Backup
#  Testing (quality checks and HCMT)
#  do the same with github actions
#  opotinally setup basic resources (VNET, Subnet, Key vault, RSV, Storage Account, DNS, ...)
#  cleanup everything (unregister HANA and RSV + delete RG)

parameters:
- name: size
  displayName: HANA VM Size
  type: string
  default: 192_GB
  values:
  - 128_GB-Non-PRD
  - 160_GB-Non-PRD
  - 192_GB
  - 256_GB
  - 512_GB
  - 1.000_GB
  - 1.792_GB
  - 2.000_GB
  - 2.850_GB
  - 3.892_GB
  - 5.700_GB
  - 11.400_GB

- name: os
  displayName: Operating System
  type: string
  default: "SLES 12 SP4"
  values:
  - "RHEL 7"
  - "RHEL 8"
  - "SLES 12 SP4"
  - "SLES 12 SP5"
  - "SLES 15 SP2"

- name: sid
  displayName: HANA System ID
  type: string
  default: "HDB"

- name: nr
  displayName: HANA Instance Number (00-99)
  type: string
  default: "20"

- name: vmname
  displayName: HANA Server Name
  type: string
  default: "hanatest"

- name: location
  displayName: Target Region
  type: string
  default: "West Europe"
  values:
  - "West Europe"
  - "Germany West Central"

- name: subnet
  displayName: Target Subnet
  type: string
  default: "SAPDemoEnvironmentNetwork/subnets/sapdevsubnet"
  values:
  - "SAPDemoEnvironmentNetwork/subnets/sapdevsubnet"
  - "SAPSpokeGWC/subnets/sapdevsubnet"

- name: hanavmdeployment
  displayName: HANA VM Deployment
  type: boolean
  default: true

- name: hanadbinstallation
  displayName: HANA DB Installation
  type: boolean
  default: true

- name: hanabackupsetup
  displayName: HANA Backup Setup
  type: string
  default: "Non-PRD"
  values:
  - "Non-PRD"
  - "PRD"
  - "None"

- name: qualitychecks
  displayName: HANA quality checks
  type: boolean
  default: False

- name: hcmt
  displayName: HANA performance checks
  type: boolean
  default: False

- name: cleanup
  displayName: Remove everything at the end
  type: boolean
  default: False

trigger:
  none

pool:
  name: Default

variables:
  backuptype: ${{ parameters.hanabackupsetup }}
  hanadbinst: ${{ parameters.hanadbinstallation }}
  # perform the backup setup only when the DB will be installed
  # backuptodo: $[and (ne(variables['backuptype'], 'None'), eq(variables['hanadbinst'], true)) ]
  backuptodo: $[ ne(variables['backuptype'], 'None') ]
  hcmttest: ${{ parameters.hcmt }}
  finalcleanup: ${{ parameters.cleanup }}

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: hana

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'SAP HANA VM Deployment via ARM'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(subscriptionname)'
        subscriptionId: '$(subscription)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'rg-HANA-${{ parameters.sid }}'
        location: ${{ parameters.location }}
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/mimergel/sap-hana-vm/$(Build.SourceBranchName)/azuredeploy.json'
        overrideParameters: '-adminUsername "$(adminuser)" -vmNameInput "${{ parameters.vmname }}" -hanaSystemId "${{ parameters.sid }}" -instancenumber "${{ parameters.nr }}" -hanaSystemSize "${{ parameters.size }}" -osType "${{ parameters.os }}" -adminPasswordOrKey "$(sshkey)" -subnetId "/subscriptions/$(subscription)/resourceGroups/SAPonAzureTrial/providers/Microsoft.Network/virtualNetworks/${{ parameters.subnet }}" -Backup "${{ parameters.hanabackupsetup }}"'
        deploymentMode: 'Complete'
      condition: eq(${{ parameters.hanavmdeployment }}, true)

    - script: ssh-keygen -f "/home/mimergel/.ssh/known_hosts" -R ${{ parameters.vmname }}.$(privatednszone)
      displayName: Remove known_hosts entries from former runs
      failOnStderr: false

    - script: nslookup ${{ parameters.vmname }}.$(privatednszone) ; while [ $? -ne 0 ]; do nslookup ${{ parameters.vmname }}.$(privatednszone) ; sleep 3 ; done
      displayName: Wait until DNS resolves "${{ parameters.vmname }}"
      failOnStderr: false

    - task: Ansible@0
      displayName: 'OS Preparations (Ansible)'
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'os-settings_playbook.yml'
        inventoriesAgentMachine: inlineContent
        inventoryInlineContentAgentMachine: |
          [hana]
          ${{ parameters.vmname }}.$(privatednszone)
        args: -v -e sap_sid=${{ parameters.sid }} -e sap_hostname=${{ parameters.vmname }} -e sap_instancenum=${{ parameters.nr }}
        failOnStdErr: false
      condition: eq(${{ parameters.hanadbinstallation }}, true)

    - task: Ansible@0
      displayName: 'HANA Installation (Ansible)'
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'saphana-install_playbook.yml'
        inventoriesAgentMachine: inlineContent
        inventoryInlineContentAgentMachine: |
          [hana]
          ${{ parameters.vmname }}.$(privatednszone)
        args: -v -e sap_sid=${{ parameters.sid }} -e sap_hostname=${{ parameters.vmname }} -e sap_instancenum=${{ parameters.nr }}
        failOnStdErr: false
      condition: eq(${{ parameters.hanadbinstallation }}, true)

    - task: Ansible@0
      displayName: 'HANA Backup Preparations (Ansible)'
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'backup_playbook.yml'
        inventoriesAgentMachine: inlineContent
        inventoryInlineContentAgentMachine: |
          [hana]
          ${{ parameters.vmname }}.$(privatednszone)
        args: -v -e sap_sid=${{ parameters.sid }} -e sap_hostname=${{ parameters.vmname }} -e sap_instancenum=${{ parameters.nr }}
        failOnStdErr: false
      condition: eq(variables.backuptodo, true)

    - task: PowerShell@2
      displayName: 'HANA Backup Registration and Execution'
      # https://docs.microsoft.com/en-us/azure/backup/tutorial-sap-hana-backup-cli 
      inputs:
        # Register the SAP HANA Instance
        targetType: 'inline'
        script: |
          az backup container register --resource-group ${RSV_RG} \
            --vault-name ${RSV} \
            --workload-type SAPHANA \
            --backup-management-type AzureWorkload \
            --resource-id $(az vm show -g 'rg-HANA-${{ parameters.sid }}' -n ${{ parameters.vmname }} --query id --output tsv)
          # Enable Protection systemdb
          az backup protection enable-for-azurewl --resource-group ${RSV_RG} \
            --vault-name ${RSV} \
            --policy-name HANA-${{ parameters.hanabackupsetup }} \
            --protectable-item-name "saphanadatabase;${{ parameters.sid }};systemdb"  \
            --protectable-item-type SAPHANADatabase \
            --server-name ${{ parameters.vmname }} \
            --workload-type SAPHANA \
            --output table
          # Enable Protection Tenant DB
          az backup protection enable-for-azurewl --resource-group ${RSV_RG} \
            --vault-name ${RSV} \
            --policy-name HANA-${{ parameters.hanabackupsetup }} \
            --protectable-item-name "saphanadatabase;${{ parameters.sid }};${{ parameters.sid }}"  \
            --protectable-item-type SAPHANADatabase \
            --server-name ${{ parameters.vmname }} \
            --workload-type SAPHANA \
            --output table
          # Backup systemdb
          az backup protection backup-now --resource-group ${RSV_RG} \
            --vault-name ${RSV} \
            --item-name 'saphanadatabase;${{ parameters.sid }};systemdb' \
            --container-name 'VMAppContainer;Compute;rg-HANA-${{ parameters.sid }};${{ parameters.vmname }}' \
            --backup-type full \
            --output table
          # Backup Tenant DB
          az backup protection backup-now --resource-group ${RSV_RG} \
            --vault-name ${RSV} \
            --item-name 'saphanadatabase;${{ parameters.sid }};${{ parameters.sid }}' \
            --container-name 'VMAppContainer;Compute;rg-HANA-${{ parameters.sid }};${{ parameters.vmname }}' \
            --backup-type full \
            --output table
        errorActionPreference: 'continue'
        showWarnings: true
      condition: eq(variables.backuptodo, true)

- stage: Test
  # dependsOn: Deploy
  condition: eq(${{ parameters.hcmt }}, true)
  jobs:
  - job: Test
    steps:
    - task: Ansible@0
      displayName: 'Run HCMT (Ansible)'
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'hcmt_playbook.yml'
        inventoriesAgentMachine: inlineContent
        inventoryInlineContentAgentMachine: |
          [hana]
          ${{ parameters.vmname }}.$(privatednszone)
        args: -v 
        failOnStdErr: false
      condition: eq(variables.hcmttest, true)

- stage: Cleanup
  jobs:
  - job: Cleanup
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(subscriptionname)'
        subscriptionId: '$(subscription)'
        action: 'DeleteRG'
        resourceGroupName: 'rg-HANA-${{ parameters.sid }}'
      condition: eq(variables.finalcleanup, true)
      # todo: unregister HANA and remove from RSV