# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: size
  displayName: HANA VM Size
  type: string
  default: 256_GB
  values:
  - 128_GB-Non-PRD
  - 160_GB-Non-PRD
  - 192_GB
  - 256_GB
  - 512_GB
  - 1.000_GB
  - 1.792_GB
  - 2.000_GB
  - 2.850_GB
  - 3.892_GB
  - 5.700_GB
  - 11.400_GB

- name: os
  displayName: Operating System
  type: string
  default: "SLES 12 SP4"
  values:
  - "RHEL 7"
  - "RHEL 8"
  - "SLES 12 SP4"
  - "SLES 12 SP5"
  - "SLES 15 SP2"

- name: sid
  displayName: HANA System ID
  type: string
  default: "HDB"

- name: vmname
  displayName: HANA Server Name
  type: string
  default: "hanatest"

- name: location
  displayName: Target Region
  type: string
  default: "West Europe"
  values:
  - "West Europe"
  - "Germany West Central"

- name: subnet
  displayName: Target Subnet
  type: string
  default: "SAPDemoEnvironmentNetwork/subnets/sapdevsubnet"
  values:
  - "SAPDemoEnvironmentNetwork/subnets/sapdevsubnet"
  - "SAPSpokeGWC/subnets/sapdevsubnet"

- name: hanadbinstallation
  displayName: HANA DB Installation
  type: boolean
  default: true

- name: hanabackupsetup
  displayName: HANA Backup Setup
  type: boolean
  default: true

trigger:
  none

pool:
  # Using my own deployment agents instead of devops agents 
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops 
  name: Default

steps:
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: hana

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'SAP HANA VM Deployment via ARM'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(subscriptionname)'
    subscriptionId: '$(subscription)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'HANA-Test-$(Build.BuildId)'
    location: ${{ parameters.location }}
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/mimergel/sap-hana-vm/main/azuredeploy.json'
    overrideParameters: '-adminUsername "$(adminuser)" -vmNameInput "${{ parameters.vmname }}" -hanaSystemId "${{ parameters.sid }}" -hanaSystemSize "${{ parameters.size }}" -osType "${{ parameters.os }}" -adminPasswordOrKey "$(sshkey)" -subnetId "/subscriptions/$(subscription)/resourceGroups/SAPonAzureTrial/providers/Microsoft.Network/virtualNetworks/${{ parameters.subnet }}"'
    deploymentMode: 'Complete'

- script: ssh-keygen -f "/home/mimergel/.ssh/known_hosts" -R "${{ parameters.vmname }}".'$(privatednszone)'
  displayName: Remove known_hosts entries from former runs
  failOnStderr: false

- script: nslookup "${{ parameters.vmname }}".'$(privatednszone)' ; while [ $? -ne 0 ]; do nslookup "${{ parameters.vmname }}".'$(privatednszone)' ; sleep 3 ; done
  displayName: Wait until DNS resolves "${{ parameters.vmname }}"
  failOnStderr: false

- task: Ansible@0
  displayName: 'Ansible Playbook for HANA Installation'
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'single_node_playbook.yml'
    inventoriesAgentMachine: inlineContent
    inventoryInlineContentAgentMachine: |
     [hana]
     "${{ parameters.vmname }}".'$(privatednszone)'
    args: -v -e sap_sid="${{ parameters.sid }}" sap_hostname="${{ parameters.vmname }}"
    failOnStdErr: false
  condition: $[eq(${{ parameters.hanadbinstallation }}, true)]  

- task: Ansible@0
  displayName: 'Ansible Playbook for HANA Backup'
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'hana_backup_playbook.yml'
    inventoriesAgentMachine: inlineContent
    inventoryInlineContentAgentMachine: |
     [hana]
     "${{ parameters.vmname }}".'$(privatednszone)'
    args: -v -e sap_sid="${{ parameters.sid }}" sap_hostname="${{ parameters.vmname }}"
    failOnStdErr: false
  condition: $[eq(${{ parameters.hanabackupsetup }}, true)]  