---
- name: download msawb-plugin-config-com-sap-hana.sh
  get_url:
    url: "{{ url_hana_backup_script }}"
    dest: /tmp/msawb-plugin-config-com-sap-hana.sh
    mode: 0750
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

# The following must be set on the deployment agent server in /etc/ansible/ansible.cfg
# allow_world_readable_tmpfiles = True
# otherwise the underprivileged user sidadm won't be able to execute the command

- name: Setup SYSTEM user for Backup integration
  become: yes
  become_user: "{{ sap_sid|lower }}adm"
  command: /usr/sap/"{{ sap_sid }}"/HDB"{{ sap_instancenum }}"/exe/hdbuserstore Set SYSTEM "{{ sap_hostname }}":3"{{ sap_instancenum }}"13@SYSTEMDB SYSTEM "{{ pw_db_system }}"

- name: Run integration script
  command: '/tmp/msawb-plugin-config-com-sap-hana.sh -sk SYSTEM'

- name: Delete SYSTEM user after Backup integration
  become: yes
  become_user: "{{ sap_sid|lower }}adm"
  command: /usr/sap/"{{ sap_sid }}"/HDB"{{ sap_instancenum }}"/exe/hdbuserstore Delete SYSTEM
