---

# Swap Space
- name: Ensure variables are available
  include_vars:
    file: "../vars/os-vars.yml"

- include_tasks: swap.yml
  loop: "{{ sap_swap }}"
  when: item.tier == "HANA" or item.tier == "all"

# SUSE bug 1167134
- name:         "Ensure DHCLIENT_SET_HOSTNAME is set to no for SLES"
  lineinfile:
    path:       /etc/sysconfig/network/dhcp
    regexp:     '^DHCLIENT_SET_HOSTNAME='
    line:       DHCLIENT_SET_HOSTNAME="no"
  when:         ansible_os_family|upper == 'SUSE'

# Update all packages SLES
- name: Update all packages on OpenSUSE/SUSE Linux
  zypper:
    name: '*'
    state: latest
    type: patch
  environment:
    ZYPP_LOCK_TIMEOUT: 300
  when: ansible_os_family|upper == "SUSE"

# Update all packages RHEL
- name: Update all installed packages using YUM module
  yum:
    name: '*'
    state: latest
    locktimeout: 300
  when: ansible_os_family|upper == "REDHAT"

# Hang-on until previous package installations completely finishes and removes the lock
- name:             Wait until package installation lock is removed
  command:          "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

# Package Installation
- name:             Import package list
  include_vars:     os-vars.yml

- name:             "Install OS packages: {{ ansible_os_family|upper }}-{{ ansible_distribution_major_version }}"
  package:
    name:           "{{ item }}" 
    state:          present
  environment:
    ZYPP_LOCK_TIMEOUT: 300
    lock_timeout: 300
  loop:             "{{ packages[ansible_os_family|lower + ansible_distribution_major_version] }}"

# SAP Note 2205917 - SAP HANA DB Recommended OS settings for SLES 12 / SLES for SAP Applications 12
# SAP Note 2684254 - SAP HANA DB: Recommended OS settings for SLES 15 / SLES for SAP Applications 15
# SAP Note 2578899 - SUSE Linux Enterprise Server 15: Installation Note 
# SAP Note 2292690 - SAP HANA DB: Recommended OS settings for RHEL 7 
# SAP Note 2777782 - SAP HANA DB: Recommended OS Settings for RHEL 8

- name:     Task Disable Transparent Hugepages & Configure Processor C-States 1
  command:    "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

- name:     Task Disable Transparent Hugepages & Configure Processor C-States 2
  lineinfile: 
     dest:    /etc/default/grub 
     regexp:  "GRUB_CMDLINE_LINUX=" 
     line:    "GRUB_CMDLINE_LINUX='crashkernel=auto  @ vconsole.keymap=us @kernel_arguments: transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1'"

- name:     Task Disable Transparent Hugepages & Configure Processor C-States 3
  command:    grub2-mkconfig -o /boot/grub2/grub.cfg

- name:     "Manual preparation for {{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}"
  include_tasks:    "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}-os_config.yml"
  when:     ansible_os_family|upper == "REDHAT" or
            ansible_os_family|upper == "SUSE"
