---
# SLES 12 specifics

- name: Task Tweak the Default System Settings for SAP HANA 1 
  command: "saptune solution apply HANA"

- name: Task Tweak the Default System Settings for SAP HANA 2
  command: "saptune daemon start"
  